# Generated by Django 5.2.9 on 2025-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alumni_year',
            field=models.DateField(blank=True, null=True, verbose_name='Alumni Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False, verbose_name='Is Alumni'),
        ),
    ]
