# Generated by Django 5.2.9 on 2025-12-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
        ('students', '0002_student_alumni_year_student_is_alumni'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school', 'date'], name='attendance_school_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendance_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='student_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_class', 'section'], name='student_class_section_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_number'], name='student_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='student_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_year'], name='student_academic_year_idx'),
        ),
    ]
