# Generated by Django 5.2.9 on 2025-12-26 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
        ('students', '0004_student_documents_and_medical_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthistory',
            options={'ordering': ['-academic_year__start_date'], 'verbose_name': 'Student History', 'verbose_name_plural': 'Student Histories'},
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='attendance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Attendance %'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='class_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rank in class', null=True, verbose_name='Class Rank'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='conduct',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs Improvement'), ('UNSATISFACTORY', 'Unsatisfactory')], default='GOOD', max_length=20, verbose_name='Conduct'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='days_present',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Days Present'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='detention_reason',
            field=models.TextField(blank=True, help_text='Reason if student was detained', verbose_name='Detention Reason'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (Outstanding)'), ('A', 'A (Excellent)'), ('B+', 'B+ (Very Good)'), ('B', 'B (Good)'), ('C+', 'C+ (Above Average)'), ('C', 'C (Average)'), ('D', 'D (Below Average)'), ('E', 'E (Marginal)'), ('F', 'F (Fail)')], help_text='Overall grade for the year', max_length=5, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='max_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum possible marks', max_digits=7, null=True, verbose_name='Maximum Marks'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall percentage obtained', max_digits=5, null=True, verbose_name='Percentage'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='promoted_to_class',
            field=models.ForeignKey(blank=True, help_text='Class promoted to (null if detained/graduated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_histories', to='schools.class'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='promotion_status',
            field=models.CharField(choices=[('PROMOTED', 'Promoted'), ('DETAINED', 'Detained'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred'), ('WITHDRAWN', 'Withdrawn')], default='PROMOTED', max_length=20, verbose_name='Promotion Status'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='remarks',
            field=models.TextField(blank=True, help_text='Teacher/Principal remarks', verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='section_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rank in section', null=True, verbose_name='Section Rank'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total marks obtained in all subjects', max_digits=7, null=True, verbose_name='Total Marks Obtained'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='total_working_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Working Days'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='studenthistory',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='studenthistory',
            index=models.Index(fields=['school', 'academic_year'], name='shistory_school_year_idx'),
        ),
        migrations.AddIndex(
            model_name='studenthistory',
            index=models.Index(fields=['student', 'academic_year'], name='shistory_student_year_idx'),
        ),
        migrations.AddIndex(
            model_name='studenthistory',
            index=models.Index(fields=['promotion_status'], name='shistory_promotion_idx'),
        ),
    ]
