# Generated by Django 5.2.9 on 2026-01-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studenthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gr_number',
            field=models.CharField(blank=True, help_text='Permanent General Register No', max_length=50, null=True, unique=True, verbose_name='GR Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(help_text='Dynamic Roll No (e.g. 10A-001)', max_length=50, verbose_name='Class Roll No'),
        ),
    ]
