# Generated by Django 5.2.9 on 2025-12-15 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('domain', models.CharField(blank=True, help_text='Custom domain or subdomain', max_length=255, null=True, verbose_name='Domain')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=10, verbose_name='Default Language')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
                ('signature_url', models.URLField(blank=True, null=True, verbose_name='Principal Signature URL')),
                ('watermark_url', models.URLField(blank=True, null=True, verbose_name='Report Watermark URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Class 10', max_length=50, verbose_name='Class Name')),
                ('order', models.PositiveIntegerField(default=0, help_text='For sorting, e.g. 10')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. 2024-25', max_length=20, verbose_name='Year Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. A', max_length=50, verbose_name='Section Name')),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.school')),
            ],
            options={
                'unique_together': {('parent_class', 'name')},
            },
        ),
    ]
