# Generated by Django 5.2.9 on 2025-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Geo Latitude'),
        ),
        migrations.AddField(
            model_name='school',
            name='gps_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Geo Longitude'),
        ),
    ]
