# Generated by Django 5.2.9 on 2025-12-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_gps_lat_school_gps_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo_url',
            field=models.TextField(blank=True, null=True, verbose_name='Logo Data'),
        ),
        migrations.AlterField(
            model_name='school',
            name='signature_url',
            field=models.TextField(blank=True, null=True, verbose_name='Principal Signature Data'),
        ),
        migrations.AlterField(
            model_name='school',
            name='watermark_url',
            field=models.TextField(blank=True, null=True, verbose_name='Report Watermark Data'),
        ),
    ]
