# Generated by Django 5.2.9 on 2025-12-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_logo_url_alter_school_signature_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='min_hours_full_day',
            field=models.FloatField(default=6.0, verbose_name='Min Hours for Full Day'),
        ),
        migrations.AddField(
            model_name='school',
            name='min_hours_half_day',
            field=models.FloatField(default=4.0, verbose_name='Min Hours for Half Day'),
        ),
    ]
