# Generated by Django 5.2.9 on 2025-12-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_min_hours_full_day_school_min_hours_half_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='salary_calculation_day',
            field=models.PositiveIntegerField(default=30, help_text='Day of month to generate salary (e.g. 30)', verbose_name='Salary Calculation Day'),
        ),
    ]
