# Generated by Django 5.2.9 on 2025-12-23 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'created_at'], name='homework_school_created_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['class_assigned'], name='homework_class_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['due_date'], name='homework_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['created_at'], name='homework_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['school', 'date'], name='notice_school_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_active'], name='notice_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['target_role'], name='notice_target_role_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['date'], name='notice_date_idx'),
        ),
    ]
