# Generated by Django 5.2.9 on 2025-12-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='geofence_radius',
            field=models.PositiveIntegerField(default=50, help_text='Radius in meters for attendance marking validation', verbose_name='Geofence Radius (Meters)'),
        ),
    ]
