# Generated by Django 5.2.9 on 2025-12-26 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
        ('students', '0004_student_documents_and_medical_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stage Name')),
                ('order', models.PositiveIntegerField(verbose_name='Sequence Order')),
                ('is_required', models.BooleanField(default=True)),
                ('requires_documents', models.BooleanField(default=False, help_text='Documents must be uploaded at this stage')),
                ('requires_payment', models.BooleanField(default=False, help_text='Payment required to proceed')),
                ('requires_assessment', models.BooleanField(default=False, help_text='Assessment/test required')),
                ('auto_notify_parent', models.BooleanField(default=False)),
                ('notification_message', models.TextField(blank=True, help_text='SMS/Email content (use {name}, {stage})')),
                ('required_approver_role', models.CharField(choices=[('ANY', 'Any Staff'), ('TEACHER', 'Teacher'), ('OFFICE_STAFF', 'Office Staff'), ('ACCOUNTANT', 'Accountant'), ('PRINCIPAL', 'Principal Only'), ('SCHOOL_ADMIN', 'School Admin')], default='OFFICE_STAFF', max_length=50)),
                ('auto_advance', models.BooleanField(default=False, help_text='Auto-advance to next stage on completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workflow Stage',
                'verbose_name_plural': 'Workflow Stages',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enquiry_photos/')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Parent/Guardian Name')),
                ('parent_mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('parent_occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('previous_school_name', models.CharField(blank=True, max_length=200, verbose_name='Previous School Name')),
                ('previous_class', models.CharField(blank=True, max_length=50, verbose_name='Previous Class')),
                ('previous_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('filled_at', models.DateTimeField(auto_now_add=True)),
                ('filled_via', models.CharField(choices=[('MOBILE', 'Mobile App'), ('WEB', 'Web Dashboard'), ('WALK_IN', 'Walk-in/Manual'), ('ONLINE', 'Online Form')], default='WALK_IN', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('APPROVED', 'Approved - Ready for Admission'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Student'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('rejection_reason', models.TextField(blank=True)),
                ('referred_by', models.CharField(blank=True, help_text='Who referred this student', max_length=200, verbose_name='Referred By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.academicyear')),
                ('class_applied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='schools.class')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_admitted', to=settings.AUTH_USER_MODEL)),
                ('converted_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_enquiry', to='students.student')),
                ('filled_by', models.ForeignKey(help_text='Teacher/Staff who filled this enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_filled', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='schools.school')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_enquiries', to='admissions.workflowstage')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('PREV_MARKSHEET', 'Previous Marksheet'), ('TC', 'Transfer Certificate'), ('AADHAR', 'Aadhar Card'), ('PHOTO', 'Passport Photo'), ('ADDRESS_PROOF', 'Address Proof'), ('CASTE_CERT', 'Caste Certificate'), ('INCOME_CERT', 'Income Certificate'), ('OTHER', 'Other Document')], max_length=50)),
                ('document_name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='enquiry_docs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_remarks', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.enquiry')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_enquiry_docs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquiry Document',
                'verbose_name_plural': 'Enquiry Documents',
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Assessment Name')),
                ('assessment_type', models.CharField(choices=[('WRITTEN', 'Written Test'), ('ORAL', 'Oral/Interview'), ('PRACTICAL', 'Practical Test'), ('DOCUMENT', 'Document Verification'), ('PAYMENT', 'Fee Payment'), ('APPROVAL', 'Manual Approval')], default='APPROVAL', max_length=50)),
                ('max_marks', models.PositiveIntegerField(default=100, help_text='Maximum marks (0 for pass/fail only)')),
                ('passing_marks', models.PositiveIntegerField(default=40)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions for the assessor')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='admissions.workflowstage')),
            ],
            options={
                'verbose_name': 'Assessment Template',
                'verbose_name_plural': 'Assessment Templates',
                'ordering': ['stage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('workflow_type', models.CharField(choices=[('ADMISSION', 'Admission Enquiry'), ('SCHOLARSHIP', 'Scholarship Application'), ('TRANSPORT', 'Transport Request'), ('HOSTEL', 'Hostel Application'), ('CUSTOM', 'Custom Workflow')], default='ADMISSION', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this workflow type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='schools.school')),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='admissions.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='admissions.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='EnquiryAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.assessmenttemplate')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='admissions.enquiry')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'verbose_name_plural': 'Assessment Results',
                'unique_together': {('enquiry', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='EnquiryStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='admissions.enquiry')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.workflowstage')),
            ],
            options={
                'verbose_name': 'Enquiry Stage Progress',
                'verbose_name_plural': 'Enquiry Stage Progress',
                'ordering': ['stage__order'],
                'unique_together': {('enquiry', 'stage')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='workflowstage',
            unique_together={('template', 'order')},
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['school', 'status'], name='enquiry_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['filled_by'], name='enquiry_filled_by_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['class_applied'], name='enquiry_class_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['created_at'], name='enquiry_created_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['enquiry_id'], name='enquiry_id_idx'),
        ),
    ]
