# Generated by Django 5.2.9 on 2025-12-23 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_staffsalarystructure'),
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
        ('students', '0003_attendance_attendance_school_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'academic_year'], name='feestructure_school_year_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['class_assigned'], name='feestructure_class_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['category'], name='feestructure_category_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'status'], name='invoice_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'created_at'], name='invoice_student_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoice_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_id'], name='invoice_id_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['school', 'month'], name='salary_school_month_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['staff', 'month'], name='salary_staff_month_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['is_paid'], name='salary_is_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['salary_id'], name='salary_id_idx'),
        ),
    ]
