# Generated by Django 5.2.9 on 2025-12-24 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_feestructure_feestructure_school_year_idx_and_more'),
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
        ('students', '0004_student_documents_and_medical_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('BONAFIDE', 'Bonafide Certificate'), ('TC', 'Transfer Certificate'), ('LC', 'Leaving Certificate'), ('MIGRATION', 'Migration Certificate'), ('CHARACTER', 'Character Certificate'), ('CONDUCT', 'Conduct Certificate'), ('STUDY', 'Study Certificate'), ('ATTENDANCE', 'Attendance Certificate'), ('SPORTS', 'Sports Participation'), ('ACHIEVEMENT', ' Certificate'), ('FEE_CLEARANCE', 'Fee Clearance Certificate'), ('COURSE_COMPLETION', 'Course Completion'), ('CUSTOM', 'Custom Certificate')], help_text='Type of certificate', max_length=50)),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Fee amount for this certificate type', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether fee is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], help_text='Percentage or fixed amount discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 50 for 50%) or fixed amount (e.g., 5000)', max_digits=10)),
                ('reason', models.CharField(help_text='e.g., Merit Scholarship, Sibling Discount, Financial Aid', max_length=200)),
                ('valid_from', models.DateField(help_text='Start date for discount')),
                ('valid_until', models.DateField(help_text='End date for discount')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installment_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('installment_number', models.IntegerField(help_text='1, 2, 3, etc.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this installment', max_digits=10, verbose_name='Installment Amount')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for this installment', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this invoice', null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to this invoice', max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Reason for discount (e.g., Scholarship, Sibling Discount)', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_term',
            field=models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2'), ('TERM3', 'Term 3'), ('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly'), ('ONETIME', 'One-Time')], default='ANNUAL', help_text='Payment term for this invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='Whether this invoice has been settled for the year'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late payment fee charged', max_digits=10, verbose_name='Late Fee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_applied_date',
            field=models.DateField(blank=True, help_text='Date when late fee was applied', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='settled_date',
            field=models.DateField(blank=True, help_text='Date when invoice was settled', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='settlement_note',
            field=models.TextField(blank=True, help_text='Notes about settlement'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['academic_year', 'is_settled'], name='invoice_year_settled_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fee_term'], name='invoice_term_idx'),
        ),
        migrations.AddField(
            model_name='certificatefee',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all fees', null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.feecategory'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='students.student'),
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='certificatefee',
            index=models.Index(fields=['school', 'is_active'], name='certfee_school_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificatefee',
            unique_together={('school', 'certificate_type')},
        ),
        migrations.AddIndex(
            model_name='feediscount',
            index=models.Index(fields=['school', 'student'], name='discount_school_student_idx'),
        ),
        migrations.AddIndex(
            model_name='feediscount',
            index=models.Index(fields=['academic_year', 'is_active'], name='discount_year_active_idx'),
        ),
        migrations.AddIndex(
            model_name='feediscount',
            index=models.Index(fields=['student', 'is_active'], name='discount_student_active_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['school', 'status'], name='installment_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['invoice', 'installment_number'], name='installment_invoice_num_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['due_date'], name='installment_due_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeinstallment',
            unique_together={('invoice', 'installment_number')},
        ),
    ]
