# Generated by Django 5.2.9 on 2025-12-26 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_certificatefee_feediscount_feeinstallment_and_more'),
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Staff who physically collected the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='remarks',
            field=models.TextField(blank=True, help_text='Any notes about this payment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('NEFT', 'NEFT/RTGS'), ('CARD', 'Debit/Credit Card')], max_length=50, verbose_name='Payment Mode'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['school', 'date'], name='receipt_school_date_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['invoice'], name='receipt_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['created_at'], name='receipt_created_at_idx'),
        ),
    ]
