# Generated by Django 5.2.9 on 2026-01-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_receipt_collected_by_receipt_created_at_and_more'),
        ('schools', '0010_school_geofence_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Allocated Amount')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeBreakup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Amount')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='feestructure',
            name='feestructure_class_idx',
        ),
        migrations.RemoveIndex(
            model_name='feestructure',
            name='feestructure_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_school_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_student_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_due_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_year_settled_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_term_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='receipt_school_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='receipt_invoice_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='receipt_created_at_idx',
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_reason',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fee_term',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_settled',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='late_fee',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='late_fee_applied_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='settled_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='settlement_note',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='remarks',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.section'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.academicyear'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'class_assigned', 'section', 'category')},
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.receipt'),
        ),
        migrations.AddField(
            model_name='studentfeebreakup',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feecategory'),
        ),
        migrations.AddField(
            model_name='studentfeebreakup',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakups', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='fee_breakup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.studentfeebreakup'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfeebreakup',
            unique_together={('invoice', 'head')},
        ),
    ]
