# Generated by Django 5.2.9 on 2026-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_paymentallocation_studentfeebreakup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatefee',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GST Percentage (e.g. 18.00)', max_digits=5, verbose_name='GST Rate (%)'),
        ),
        migrations.AddField(
            model_name='certificatefee',
            name='is_tax_inclusive',
            field=models.BooleanField(default=False, help_text='If True, amount includes tax. If False, tax is added on top.', verbose_name='Is Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='certificatefee',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Round Off Amount'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GST Percentage (e.g. 18.00)', max_digits=5, verbose_name='GST Rate (%)'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='is_tax_inclusive',
            field=models.BooleanField(default=False, help_text='If True, amount includes tax. If False, tax is added on top.', verbose_name='Is Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Round Off Amount'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Round Off Amount'),
        ),
        migrations.AddField(
            model_name='studentfeebreakup',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base Amount'),
        ),
        migrations.AddField(
            model_name='studentfeebreakup',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax Amount'),
        ),
    ]
