# Generated by Django 5.2.9 on 2026-01-08 08:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_certificatefee_gst_rate_and_more'),
        ('schools', '0010_school_geofence_radius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-month']},
        ),
        migrations.RemoveIndex(
            model_name='salary',
            name='salary_is_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='salary',
            name='salary_id_idx',
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('staff', 'month')},
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='school',
        ),
        migrations.AddField(
            model_name='salary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salary',
            name='earnings',
            field=models.JSONField(default=dict, verbose_name='Earnings Breakdown'),
        ),
        migrations.AddField(
            model_name='salary',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='loss_of_pay_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffsalarystructure',
            name='allowances',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of allowance names and amounts', verbose_name='Allowances'),
        ),
        migrations.AddField(
            model_name='staffsalarystructure',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base salary amount', max_digits=12, verbose_name='Basic Salary'),
        ),
        migrations.AddField(
            model_name='staffsalarystructure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffsalarystructure',
            name='deductions',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of deduction names and amounts', verbose_name='Deductions'),
        ),
        migrations.AddField(
            model_name='staffsalarystructure',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Net Salary (Est)'),
        ),
        migrations.AddField(
            model_name='staffsalarystructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='salary',
            name='deductions',
        ),
        migrations.AddField(
            model_name='salary',
            name='deductions',
            field=models.JSONField(default=dict, verbose_name='Deductions Breakdown'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Salary'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['status'], name='salary_status_idx'),
        ),
        migrations.RemoveField(
            model_name='salary',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='paid_leaves',
        ),
    ]
