# Generated by Django 5.2.9 on 2026-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_salary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='GST Rate (%)'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_tax_inclusive',
            field=models.BooleanField(default=False, verbose_name='Tax Inclusive'),
        ),
    ]
