# Generated by Django 5.2.9 on 2025-12-18 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Driver Age'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='Driver Mobile'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Driver Name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_upto',
            field=models.DateField(blank=True, null=True, verbose_name='Fitness Valid Upto'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_driven', to=settings.AUTH_USER_MODEL),
        ),
    ]
