# Generated by Django 5.2.9 on 2025-12-15 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='Qualification')),
                ('subjects', models.CharField(help_text='Comma separated subjects', max_length=500, verbose_name='Subjects')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Experience (Years)')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Check In')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Check Out')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Latitude')),
                ('gps_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Longitude')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('HALF_DAY', 'Half Day')], default='ABSENT', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance',
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
