# Generated by Django 5.2.9 on 2025-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='correction_reason',
            field=models.TextField(blank=True, help_text='Reason if modified manually', verbose_name='Correction Reason'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='source',
            field=models.CharField(choices=[('WEB_MANUAL', 'Web Manual'), ('QR_GEO', 'QR Geo-Fenced'), ('SYSTEM', 'System Auto')], default='SYSTEM', max_length=20, verbose_name='Source'),
        ),
    ]
