# Generated by Django 5.2.9 on 2025-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffattendance_correction_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='source',
            field=models.CharField(choices=[('WEB_MANUAL', 'Web Manual'), ('QR_GEO', 'QR Geo-Fenced'), ('MOBILE_GPS', 'Mobile Button (GPS)'), ('SYSTEM', 'System Auto')], default='SYSTEM', max_length=20, verbose_name='Source'),
        ),
    ]
