# Generated by Django 5.2.9 on 2025-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffattendance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='can_mark_manual_attendance',
            field=models.BooleanField(default=False, verbose_name='Can Mark Manual Attendance'),
        ),
    ]
