# Generated by Django 5.2.9 on 2025-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffprofile_can_mark_manual_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Password Reset Code'),
        ),
    ]
