# Generated by Django 5.2.9 on 2025-12-23 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
        ('staff', '0005_staffprofile_reset_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['school', 'date'], name='staffatt_school_date_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'date'], name='staffatt_staff_date_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['status'], name='staffatt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['date'], name='staffatt_date_idx'),
        ),
    ]
