# Generated by Django 5.2.9 on 2025-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='can_access_attendance',
            field=models.BooleanField(default=False, help_text='Can access Attendance Module'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='can_access_certificates',
            field=models.BooleanField(default=False, help_text='Can access Certificates Module'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='can_access_finance',
            field=models.BooleanField(default=False, help_text='Can access Finance Module'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='can_access_student_records',
            field=models.BooleanField(default=False, help_text='Can access Student Records'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='can_access_transport',
            field=models.BooleanField(default=False, help_text='Can access Transport Module'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='can_use_mobile_app',
            field=models.BooleanField(default=False, help_text='Can login to Mobile App'),
        ),
    ]
