# Generated by Django 5.2.9 on 2025-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coreuser_can_access_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='can_mark_manual_attendance',
            field=models.BooleanField(default=False, help_text='Can mark attendance via GPS Button (No QR) if fail'),
        ),
    ]
