# Generated by Django 5.2.9 on 2025-12-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coreuser_can_mark_manual_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='can_manage_payroll',
            field=models.BooleanField(default=False, help_text='Can manage staff salaries and payroll'),
        ),
    ]
