# Generated by Django 5.2.9 on 2025-12-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coreuser_can_manage_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='can_manage_leaves',
            field=models.BooleanField(default=False, help_text='Can approve or reject leaves'),
        ),
    ]
