# Generated by Django 5.2.9 on 2025-12-15 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('type', models.CharField(choices=[('BONAFIDE', 'Bonafide'), ('TC', 'Transfer Certificate'), ('CHARACTER', 'Character'), ('OTHER', 'Custom')], max_length=50)),
                ('html_content', models.TextField(help_text='Use placeholders {{student_name}}, {{class}}, etc.', verbose_name='HTML Template')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name='Issued Date')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate')),
            ],
        ),
    ]
