# Generated by Django 5.2.9 on 2025-12-23 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('schools', '0009_homework_homework_school_created_idx_and_more'),
        ('students', '0003_attendance_attendance_school_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_date', '-created_at'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['school', 'type', 'name'], 'verbose_name': 'Certificate Template', 'verbose_name_plural': 'Certificate Templates'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_data',
            field=models.JSONField(default=dict, help_text='Snapshot of student and school data at time of certificate issuance', verbose_name='Certificate Data'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_revoked',
            field=models.BooleanField(default=False, verbose_name='Is Revoked'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF certificate', null=True, upload_to='certificates/pdfs/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='purpose',
            field=models.TextField(blank=True, help_text='Why this certificate was requested', verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='QR code image for verification', null=True, upload_to='certificates/qr/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revoked Date'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_reason',
            field=models.TextField(blank=True, verbose_name='Revocation Reason'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Optional expiry date', null=True, verbose_name='Valid Until'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(default='TEMP-000', editable=False, help_text='Unique code for certificate verification', max_length=20, unique=True, verbose_name='Verification Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='font_family',
            field=models.CharField(default='Times New Roman', max_length=50, verbose_name='Font Family'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='header_color',
            field=models.CharField(default='#000000', help_text='Hex color code', max_length=7, verbose_name='Header Color'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='include_logo',
            field=models.BooleanField(default=True, verbose_name='Include School Logo'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='include_qr_code',
            field=models.BooleanField(default=True, verbose_name='Include QR Verification Code'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='include_seal',
            field=models.BooleanField(default=True, verbose_name='Include School Seal'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='include_signature',
            field=models.BooleanField(default=True, verbose_name='Include Principal Signature'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('BONAFIDE', 'Bonafide Certificate'), ('TC', 'Transfer Certificate'), ('LC', 'Leaving Certificate'), ('MIGRATION', 'Migration Certificate'), ('CHARACTER', 'Character Certificate'), ('CONDUCT', 'Conduct Certificate'), ('STUDY', 'Study Certificate'), ('ATTENDANCE', 'Attendance Certificate'), ('SPORTS', 'Sports Participation'), ('ACHIEVEMENT', 'Achievement Certificate'), ('FEE_CLEARANCE', 'Fee Clearance Certificate'), ('COURSE_COMPLETION', 'Course Completion'), ('CUSTOM', 'Custom Certificate')], max_length=50, verbose_name='Certificate Type'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='html_content',
            field=models.TextField(help_text='Use placeholders like {{student_name}}, {{class_name}}, {{enrollment_number}}, etc.', verbose_name='HTML Template'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='type',
            field=models.CharField(choices=[('BONAFIDE', 'Bonafide Certificate'), ('TC', 'Transfer Certificate'), ('LC', 'Leaving Certificate'), ('MIGRATION', 'Migration Certificate'), ('CHARACTER', 'Character Certificate'), ('CONDUCT', 'Conduct Certificate'), ('STUDY', 'Study Certificate'), ('ATTENDANCE', 'Attendance Certificate'), ('SPORTS', 'Sports Participation'), ('ACHIEVEMENT', 'Achievement Certificate'), ('FEE_CLEARANCE', 'Fee Clearance Certificate'), ('COURSE_COMPLETION', 'Course Completion'), ('CUSTOM', 'Custom Certificate')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='certificatetemplate',
            unique_together={('school', 'type', 'name')},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['school', '-issued_date'], name='cert_school_date_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', '-issued_date'], name='cert_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='cert_verification_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_no'], name='cert_number_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['type'], name='cert_type_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_revoked'], name='cert_revoked_idx'),
        ),
    ]
