# Generated by Django 5.2.9 on 2025-12-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_options_and_more'),
        ('finance', '0004_feestructure_feestructure_school_year_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee charged for this certificate', max_digits=10, verbose_name='Certificate Fee'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='fee_invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice for certificate fee payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='fee_paid',
            field=models.BooleanField(default=False, help_text='Whether the certificate fee has been paid'),
        ),
    ]
