# Generated by Django 5.2.9 on 2026-01-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_fee_amount_certificate_fee_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('BONAFIDE', 'Bonafide Certificate'), ('TC', 'Transfer Certificate'), ('LC', 'Leaving Certificate'), ('MIGRATION', 'Migration Certificate'), ('CHARACTER', 'Character Certificate'), ('CONDUCT', 'Conduct Certificate'), ('STUDY', 'Study Certificate'), ('ATTENDANCE', 'Attendance Certificate'), ('SPORTS', 'Sports Participation'), ('ACHIEVEMENT', 'Achievement Certificate'), ('FEE_CLEARANCE', 'Fee Clearance Certificate'), ('COURSE_COMPLETION', 'Course Completion'), ('ID_CARD', 'Student ID Card'), ('CUSTOM', 'Custom Certificate')], max_length=50, verbose_name='Certificate Type'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='type',
            field=models.CharField(choices=[('BONAFIDE', 'Bonafide Certificate'), ('TC', 'Transfer Certificate'), ('LC', 'Leaving Certificate'), ('MIGRATION', 'Migration Certificate'), ('CHARACTER', 'Character Certificate'), ('CONDUCT', 'Conduct Certificate'), ('STUDY', 'Study Certificate'), ('ATTENDANCE', 'Attendance Certificate'), ('SPORTS', 'Sports Participation'), ('ACHIEVEMENT', 'Achievement Certificate'), ('FEE_CLEARANCE', 'Fee Clearance Certificate'), ('COURSE_COMPLETION', 'Course Completion'), ('ID_CARD', 'Student ID Card'), ('CUSTOM', 'Custom Certificate')], max_length=50),
        ),
    ]
